global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Memory;
global using XoomCore.Application.Common.Interfaces;
global using XoomCore.Application.Common.Response;
global using XoomCore.Application.RequestModels.AccessControl;
global using XoomCore.Domain.Entities.AccessControl;
global using XoomCore.Domain.Enum;
global using XoomCore.Persistence.UnitOfWorks;
